### ISSUE TITLE
Debugging the plugin

### ISSUE THREAD

**Issue by kja-xyt** [nineinchnick/trino-faker#100]
Is it possible to debug the code of the plugin? I haven't seen any documentation for that.

Thanks,
Kamil

**Comment by nineinchnick** [comment]
Yes, look for a query runner class in tests. There's a main method there. You can run it from the IDE. It's preconfigured and ready to use. Connect to it using any regular trino client, like the cli.

**Comment by nineinchnick** [comment]
You can also find me on the Trino Slack if you'll have more questions

**Comment by kja-xyt** [comment]
Thanks, it works like a charm 👍
