### ISSUE TITLE
Request for Version Tagging Alignment with Trino in trino-faker Library

### ISSUE THREAD

**Issue by alaturqua** [nineinchnick/trino-faker#99]
I'm reaching out to suggest an enhancement for the trino-faker connector's version tagging strategy. 

It would be incredibly helpful if the library could adopt a version tagging system similar to Trino's, such as using tags like `v435`, `v436`, etc. This approach would greatly simplify the process of matching the trino-faker connector version with the corresponding Trino version installed in our environment.

Implementing this change could enhance compatibility checks and streamline library updates for users working with specific Trino versions.

**Comment by nineinchnick** [comment]
On the other hand, it prevents doing multiple releases before a new Trino version is released. I don't want to have a constraint like this.

It is an interesting problem how to determine which Trino versions a particular version of this plugin would work with. Every Trino version could potentially introduce breaking changes, but it doesn't do so very often in practice. I guess I can add some integration test to determine the oldest Trino version that would work with the latest version of this plugin, and make that version easily discoverable (keep it in the README or some other property file).

**Comment by alaturqua** [comment]
I think having it in README would be nice.

**Comment by nineinchnick** [comment]
I suggested adding it to Trino: https://github.com/trinodb/trino/pull/23691. Let's see if there's any interested in that.

**Comment by nineinchnick** [comment]
The PR was merged, and the connector will be available since Trino 464.

**Comment by alaturqua** [comment]
This is great. Thank you very much for all the work.
